### ISSUE TITLE
Support multiple replicas of job-executor-service

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-sandbox/job-executor-service#104]
In order to scale up job-executor-service using multiple replicas, we need to define the following on the keptn/distributor:;

```
            - name: PUBSUB_GROUP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
```

When scaling up job-executor-service deployment, multiple instances of keptn/distributor and job-executor-service will run, but only one replica will receive the cloudevent.

# Definition of Done

- [ ] Multiple replicas of job-executor-service can run
- [ ] Only one replica will receive one CloudEvent
- [ ] Multiple CloudEvents are split across multiple replicas
