### ISSUE TITLE
Make config parsing stricter

### ISSUE THREAD

**Issue by yeahservice** [keptn-sandbox/job-executor-service#16]
Currently we do not enforce a lot or rules during the config parsing, just for an example the following configuration is valid and works:

```yaml
apiVersion: v1
actions:
  - events:
      - name: "sh.keptn.event.echo.triggered"
    tasks:
      - image: "bash"
        cmd: "echo hello"
```

With multiple configurations like that we would run into trouble since we do lookups of the actions by names. I think it would help if we require at least:
* name of the action
* name of the task
and give feedback on the bridge if config is not valid (currently it is only logged in the pod)
