### ISSUE TITLE
Support env variables from string

### ISSUE THREAD

**Issue by yeahservice** [keptn-sandbox/job-executor-service#34]
Currently one can use env with source either from `valueFrom: secret` or from `valueFrom: event`. It would also be useful to just define common environment variables, something like:

```yaml
- name: TF_DATA_DIR
  value: /tmp/.terraform
  valueFrom: string
```
