### ISSUE TITLE
Allow importing multiple fields from Kubernetes secrets into the environment

### ISSUE THREAD

**Issue by tolleiv** [keptn-sandbox/job-executor-service#51]
Hi,

the current implementation to import environment variables from Kubernetes secrets can't be used when more than one value should be retrieved from the same secret.

When you e.g. use a secret like this:

```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
```

You could not import both values at the same time mainly because the secret name is retrieved from the variable name (-> https://github.com/keptn-sandbox/job-executor-service/blob/main/pkg/k8sutils/job.go#L290 ) which would then overlap if used multiple times. The related config.yaml could look like this:
```
apiVersion: v2
actions:
  - name: "Do sth."
    events:
      - name: "sh.keptn.event.*.triggered"
    tasks:
      - name: "Task"
        image: "alpine"
       cmd:
         - env
        env:
          - name: mysecret
            value: username
            valueFrom: secret
          - name: mysecret
            value: password
            valueFrom: secret
```

My suggestion would be to allow using `valueFrom.secretKeyRef` rather than the arbitrary `secret` keyword.
