### ISSUE TITLE
Allow renaming of environment variables imported from kubernetes secrets

### ISSUE THREAD

**Issue by yeahservice** [keptn-sandbox/job-executor-service#68]
Suppose the following kubernetes secret exists:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: aGRibm9laGZibw==
```

Currently the **whole** secret (all key/value pairs) can be imported as environment variables in the following way:
```yaml
env:
  - name: mysecret
    valueFrom: secret
```

For easier reuse of secrets in different jobs it might be useful to be able to rename secrets. I propose to rework the env feature to work more like kubernetes. For the above example the new configuration would look like this:

```yaml
env:
  - name: USERNAME_ALPHA
    valueFrom:
      secretKeyRef:
        name: mysecret
        key: username
```

This allows to import one specific key `username` of the secret `locust-spine-token-exchange-dev` and make it available under the environment variable `USERNAME_ALPHA` in the container.

To still allow the import of all key/value pairs in a secret a `envFrom` syntax can be used (https://kubernetes.io/docs/concepts/configuration/secret/#use-case-as-container-environment-variables):

```yaml
envFrom:
  - secretRef:
      name: mysecret
```

Similar, referencing events goes from this:

```yaml
env:
  - name: HOST
    value: '$.data.deployment.deploymentURIsLocal[0]'
    valueFrom: event
```

to this:

```yaml
env:
  - name: HOST
    valueFrom:
      eventKeyRef:
        key: '$.data.deployment.deploymentURIsLocal[0]'
```

And for simple string values from this:

```yaml
env:
  - name: DATA_DIR
    valueFrom: string
    value: /tmp/data
```

simplifies to:

```yaml
env:
  - name: DATA_DIR
    value: /tmp/data
```
